name: Manual Deploy Web

on:
    workflow_dispatch

jobs:
    build-and-deploy-api:
        runs-on: ubuntu-latest

        defaults:
            run:
                working-directory: HomeworkManager

        steps:
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
          with:
              ref: release

        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
              creds: ${{ secrets.AZURE_CREDENTIALS }}

        - name: 'Build and push image'
          uses: azure/docker-login@v1
          with:
              login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
              username: ${{ secrets.REGISTRY_USERNAME }}
              password: ${{ secrets.REGISTRY_PASSWORD }}
        - run: |
            docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/homeworkmanagerapi:v${{ github.run_number }} -f HomeworkManager.API/Dockerfile
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/homeworkmanagerapi:v${{ github.run_number }}

        - name: 'Deploy to Azure Container Instances'
          uses: 'azure/aci-deploy@v1'
          with:
              resource-group: ${{ secrets.RESOURCE_GROUP }}
              dns-name-label: homework-manager-api
              image: ${{ secrets.REGISTRY_LOGIN_SERVER }}/homeworkmanagerapi:v${{ github.run_number }}
              registry-login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
              registry-username: ${{ secrets.REGISTRY_USERNAME }}
              registry-password: ${{ secrets.REGISTRY_PASSWORD }}
              name: aci-homeworkmanager-api
              secure-environment-variables: PRODUCTION_DB_CONNECTION_STRING="${{ secrets.PRODUCTION_DB_CONNECTION_STRING }}"
              location: 'west europe'
              
    build-and-deploy-angular:
        runs-on: ubuntu-latest

        defaults:
            run:
                working-directory: AngularClientApp

        steps:
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
          with:
              ref: release

        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
              creds: ${{ secrets.AZURE_CREDENTIALS }}

        - name: 'Build and push image'
          uses: azure/docker-login@v1
          with:
              login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
              username: ${{ secrets.REGISTRY_USERNAME }}
              password: ${{ secrets.REGISTRY_PASSWORD }}
        - run: |
            docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/homeworkmanagerangular:v${{ github.run_number }}
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/homeworkmanagerangular:v${{ github.run_number }}

        - name: 'Deploy to Azure Container Instances'
          uses: 'azure/aci-deploy@v1'
          with:
              resource-group: ${{ secrets.RESOURCE_GROUP }}
              dns-name-label: homework-manager
              image: ${{ secrets.REGISTRY_LOGIN_SERVER }}/homeworkmanagerangular:v${{ github.run_number }}
              registry-login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
              registry-username: ${{ secrets.REGISTRY_USERNAME }}
              registry-password: ${{ secrets.REGISTRY_PASSWORD }}
              name: aci-homeworkmanager-angular
              location: 'west europe'
